.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinarray_qt test_bitcoinarray_qt
clean: FORCE
	$(MAKE) -C .. bitcoinarray_qt_clean test_bitcoinarray_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinarray_qt_check
bitcoinarray-qt bitcoinarray-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinarray_qt
